server:
  port: 8080
spring:
  application:
    name: test-service
  datasource:
    url: jdbc:mysql://172.18.51.179:3307/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: sonar
    password: sonar
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
# mybatis 别名扫描
mybatis.type-aliases-package: com.sitech.learn.test.vo
  # mapper.xml文件位置,如果没有映射文件，请注释掉
mybatis.mapper-locations: classpath:mappers/*.xml
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true